#!/bin/bash
# Author: Aniverse
# https://github.com/Aniverse/aBox
#########################################################################################################
script_update=2020.03.30
script_version=r12007

usage_guide() {
s=/usr/local/bin/torrent-rename ; rm -f $s ; nano $s ; chmod 755 $s
}

#########################################################################################################

[[ $1 == -d ]] && debug=1
[[ $1 == -v ]] && verbose=1


command -v transmission-show > /dev/null || { echo -e "Error: No transmission-show" ; exit 1 ; } # apt-get install transmission-cli -y 
command -v lstor > /dev/null || { echo -e "Error: No lstor" ; exit 1 ; } # pip install pyrocore
command -v bc    > /dev/null || { echo -e "Error: No bc"    ; exit 1 ; } # apt-get install bc -y 

#########################################################################################################

function edit_trackers() {
    tracker=$(echo $tracker | sed 's/.org//')
    tracker=$(echo $tracker | sed 's/.net//')
    tracker=$(echo $tracker | sed 's/.cn//')
    tracker=$(echo $tracker | sed 's/.com//')
    tracker=$(echo $tracker | sed 's/.me//')
    tracker=$(echo $tracker | sed 's/.cc//')
    tracker=$(echo $tracker | sed 's/.xyz//')
    tracker=$(echo $tracker | sed 's/tracker.//')
    tracker=$(echo $tracker | sed 's/announce.//')
    tracker=$(echo $tracker | sed 's/a.//')
    echo $tracker | grep -q "moose.awesome-hd.me"  && tracker=AHD
    echo $tracker | grep -q world-in-hd            && tracker=WiHD
    echo $tracker | grep -q "landof.tv"            && tracker=BTN
    echo $tracker | grep -q "stackoverflow.tech"   && tracker=IPT
    echo $tracker | grep -q "flacsfor.me"          && tracker=Red
    echo $tracker | grep -q "hdts-announce"        && tracker=HDTs
    echo $tracker | grep -q "seedsfor.me"          && tracker=T
    echo $tracker | grep -q "seedingfor.me"        && tracker=S
    echo $tracker | grep -qE ":[0-9]+"  && tracker=$(echo $tracker | sed "s/:[0-9]\{1,5\}//") # remove ports
}

#########################################################################################################

[ -f tmp.ti.txt ] && rm -f tmp.ti.txt
mkdir -p renamed ; echo

for file in $PWD/*.torrent; do
    [[ $debug == 1 ]] && echo $file > tmp.ti.txt
    transmission-show "$file" >> tmp.ti.txt
    name=$(cat tmp.ti.txt | grep '  Name' | grep -Po '.*Name: \K.*')
    [[ $debug == 1 ]] && echo $name
    tracker=$(cat tmp.ti.txt | grep -v Comment | grep http | head -1 | grep -Po '\/\/(.*?)\/' | grep -Po '[^\/]+(?=\/)')
    [[ $debug == 1 ]] && echo $tracker
    torrent_file_num=$( lstor -V "$file" 2>1 | grep LISTING | grep -oP "\d+") ; [ -z $torrent_file_num ] && torrent_file_num=1
    [[ $debug == 1 ]] && echo $torrent_file_num
    size=$(lstor -V "$file" 2>1 | head -10 | grep SIZE | awk '{print $2,$3}')
    [[ $debug == 1 ]] && echo $size
    piece=$(cat tmp.ti.txt | grep "Piece Count" | awk '{print $NF}')
    psize=$(cat tmp.ti.txt | grep "Piece Size" | awk '{print $(NF-1),$NF}' | sed 's/ //')
    edit_trackers
    filename="[${tracker}][$size] $name.torrent"
    [[ $verbose == 1 ]] && filename="[${tracker}] $name [$torrent_file_num files][$psize x $piece = $size].torrent"
    [[ $debug == 1 ]] && echo "$PWD/renamed/$filename"
    cp "$file" "${PWD}/renamed/${filename}"
    echo -e "$(tput bold)$(tput setaf 3)Origin: $(tput sgr0)$(tput smul)$(basename "$file")$(tput rmul)\n$(tput bold)$(tput setaf 3)Rename: $(tput sgr0)$filename\n"
    [[ -z $debug ]] && rm -f tmp.ti.txt
done
